### ISSUE TITLE
A00: Clerk Registration/Login/Fetch API

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-ai-agent#2]
**Description:**
Users can sign up and sign in using email & password via Clerk.

For new sign ups, it should ask basic information like Name, e-mail, password.
All users that sign up will be automatically assigned as role = 1 (user).
all other relevant metadata that could be useful (like userid, date of registration, ip address etc ) can be captured in the database.
The database structure at this point is critical, need to factor in all the data points at the beginning.

There is also another role type (admin role = 2) that will provide a slightly different view and more functions in the platform.

-Create data structure and store in PostGres
Use clerk integration

**Acceptance criteria**
- Ensure the database schema structure is created and migration scripts run.
-Ensure fetching data from the API route on the frontend when logged in across all the pages.

**Comment by Benjtalkshow** [comment]
Hello @mo-jaber 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Can i work on this task? I will make PR in 3 days. Thank you

**Comment by Kachimercy1** [comment]
I'd love to work on this!

**Comment by 0xdevcollins** [comment]
I'd love to give this a go.

**Comment by saimeunt** [comment]
I'd like to work on this, having handled a similar authentication flow in the BSV faucet project, ETA 1 day.
