### ISSUE TITLE
A01: Consumer Wallet Creation 

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-ai-agent#3]
**Description:**
Create a BSV user wallet for every new registration, including private keys and seed phrases, with a toggle between testnet mode (default) and production mode (future release).

**Deliverables:**
	1. User Registration Workflow:
		- During registration, generate a new BSV wallet using the BSV TS-SDK.
		- Provide seed phrases and private key securely to the user.
	2. Testnet/Production Toggle:
		- Add a toggle in the user profile settings for switching between testnet and production.
		- Default to testnet for safer experimentation.
	3. Wallet Management UI:
		- A dashboard for users to view their public address, transaction history, and toggle between modes.
		
**Acceptance Criteria:**
	• A new wallet (private key and seed phrases) is generated for every registered user.
	• Users can securely access their seed phrases and public address post-registration.
	• The testnet toggle works correctly, with transactions directed to the appropriate network.
Steps to Implement:
	1. Wallet Generation:
		- Use BSV TS-SDK to generate wallets during user registration.
		- Store only public addresses in the database (never store private keys or seed phrases for security).
	2. Toggle Implementation:
		- Add a database field for mode (testnet or production).
		- Update backend services to route transactions based on the selected mode.
	3. UI/UX:
		- Design a user-friendly registration flow with wallet generation.
Add a clear toggle switch in user settings.

**Comment by Benjtalkshow** [comment]
Hello @mo-jaber 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 0xdevcollins** [comment]
@mo-jaber
Can I be assigned

**Comment by 0xdevcollins** [comment]
Let me try this one!
