### ISSUE TITLE
A03: Automated Code Linting and Formatting with Biome

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-ai-agent#6]
**Description:**
Add biome for formatting the and lintstage

Ensure all code is properly formatted and error-free before contributors can commit their changes. By integrating an automated tool (Biome), any issues are flagged and must be fixed before the code is accepted.

How It Works:

- Whenever a contributor tries to commit changes, the tool runs automatically to check the code for errors or formatting issues.
- If issues are found, the commit is blocked until they are resolved.
- Ensures all code is clean and consistent across the project.

Benefits:
Improves code quality and prevents errors from being pushed to the main project.
Saves time for reviewers by catching issues early.
Maintains a professional and consistent coding standard

**Comment by 0xdevcollins** [comment]
can I be assigned? @mo-jaber

**Comment by 0xdevcollins** [comment]
Could I try solving this?
