### ISSUE TITLE
A06: Transaction and Chat History Display

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-ai-agent#8]
**Description**
Enables users to view a detailed history of their blockchain transactions alongside a record of their interactions (prompts and AI responses) with the AI agent. It enhances transparency, traceability, and user engagement by consolidating all activities in one easy-to-navigate interface.

**Transaction History View:**
- Include transaction details like date, time, recipient, amount, transaction ID, and status (e.g., pending, completed).

**Chat History View:**
- Store and display user prompts and corresponding AI responses processed via LangChain and BrianAI.

**Integrated Dashboard:**
- Combine transaction and chat history into a unified, user-friendly interface.
- Provide navigation tabs for switching between transaction and chat records.

**Comment by Kachimercy1** [comment]
May I pick this up?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
Hello @mo-jaber 
I wish to be assigned to this task. I can handle it comfortably. Thanks

**Comment by saimeunt** [comment]
Hey I'd love to work on this, I'll carefully analyze how to fetch the required data and display it accordingly in the frontend, ETA is 2 days.
